# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Node.js project to Azure Function App - new-sintracap-function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '22.x' # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd
          
      # Create deployment package excluding unnecessary files
      - name: Create deployment package
        run: |
          # Create a clean directory for deployment
          mkdir deployment-package
          
          # Copy necessary files (exclude node_modules, .git, etc.)
          rsync -av --exclude='node_modules' \
                   --exclude='.git' \
                   --exclude='.github' \
                   --exclude='*.md' \
                   --exclude='.gitignore' \
                   --exclude='.env' \
                   --exclude='coverage' \
                   --exclude='test' \
                   --exclude='tests' \
                   --exclude='*.test.js' \
                   --exclude='*.spec.js' \
                   ./ deployment-package/
          
          # Install production dependencies in the deployment package
          cd deployment-package
          npm install --production
          
          # Create zip file from deployment package
          cd ..
          zip -r release.zip deployment-package/*
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          # Move contents from deployment-package to current directory
          mv deployment-package/* .
          rm -rf deployment-package
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7C98AB330DE145DE84B7AFD7A5C66785 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3C3DE0E726F94D28A41E6ED6F8CBE8DA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AEA6D25E7E5D47B8A460900851864364 }}
          
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'new-sintracap-function'
          slot-name: 'Production'
          package: '.'
          # Explicitly set these parameters for Flex Consumption
          respect-pom-xml: false
          respect-funcignore: true
          scm-do-build-during-deployment: false
          enable-oryx-build: false
